apiVersion: apps/v1
kind: Deployment
metadata:
  name: vani-agent-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vani-agent
  template:
    metadata:
      labels:
        app: vani-agent
    spec:
      containers:
        - name: vani-agent
          image: vani-agent:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: openai-secrets
                  key: OPENAI_API_KEY
            - name: WHISPER_MODEL
              value: whisper-1
            - name: GPT_MODEL
              value: gpt-4o-mini
            - name: WAKE_WORD
              value: "hello vani"
            - name: ACTIVE_WINDOW_SECONDS
              value: "120"
          resources:
            limits:
              cpu: "1"
              memory: "1Gi"
            requests:
              cpu: "250m"
              memory: "256Mi"
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: vani-agent-service
spec:
  selector:
    app: vani-agent
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP